import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <p className="header">
          Welcome to Sass Boilerplate!
        </p>

        <p className="sub-header">
          Just add to this
        </p>

        <p className="text">
          Keeping it simple
        </p>



      </main>
    </div>
  )
}
